name: task_manager_getx
description: "A new Flutter task manager project using getx."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

#-------- SDK Config --------#
environment:
  sdk: '>=3.4.0 <4.0.0'

#-------- Public Dependencies --------#
dependencies:
  flutter:
    sdk: flutter

  #-------- Imported Dependencies --------#
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.4.0
  get: ^4.6.6
  widget_and_text_animator: ^1.1.5
  gap: ^3.0.1
  http: ^1.2.2
  awesome_snackbar_content: ^0.1.3
  shared_preferences: ^2.3.1
  jwt_decoder: ^2.0.1
  ionicons: ^0.2.2
  salomon_bottom_bar: ^3.3.2
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.5

#-------- Dev Dependencies --------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#-------- App Theme Config --------#
flutter:
  uses-material-design: true

  #-------- Asset Libraries --------#
  assets:
    - assets/images/

  #-------- Fonts Libraries --------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages